### PR TITLE
fix: change core-js version to 3

### PR DESCRIPTION
**Pull request by Shawnxkwang**
update corejs verion to 3. 
using v2 generates the following error on Node v12
```
17:10:50.326  	Failed to compile.
17:10:50.327  	ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/es6.object.define-property.js' in '/vercel/workpath0/node_modules/outline-icons/lib'
17:10:50.327  	> Build error occurred
17:10:50.328  	Error: > Build failed because of webpack errors
17:10:50.328  	    at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
17:10:50.328  	    at runMicrotasks (<anonymous>)
17:10:50.328  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### CODE REVIEW

**Comment by tommoor** [comment]
Honestly I copied this config across without much thought – try removing all options from the preset-env and see if it still works for you? It does for me.

**Comment by Shawnxkwang** [comment]
@tommoor Thanks for the feedback!

Seems I cannot simply change the `core-js` version to 3 or remove the options. `@babel/polyfill` still uses `core-js v2` as a dependency but[ it's deprecated](https://babeljs.io/docs/en/babel-polyfill) and I can't find where we are using it from the code. 

After some experimentation, I'm able to get it to work by removing `@babal/polyfill` package (to prevent `core-js 2` from being added to modules) and removing the `preset-env` options at the same time. 

I've updated this PR, PTAL. My team is working on a project that uses a library with `outline-icons` as a dependency, right now this error is blocking my project from building. If you think this fix is legit, it would be awesome if you can merge it to a new release.

**Comment by tommoor** [comment]
I see, the build process was only changed in the last version so just use 1.23.0 instead until it's resolved.

It certainly shouldn't block your build!￼

**Comment by Shawnxkwang** [comment]
@tommoor thanks for the suggestion! so temporary solution I did is fixing the version of outline-icons to 1.23.0 which prevents the error.

**Comment by dmeents** [comment]
This appears to be impacting outline/rich-markdown-editor as well, as it will not run locally or build. It outputs the same error message as above.

**Comment by tommoor** [comment]
Thanks @Shawnxkwang – went with #18, but it should be resolved

**Pull request closed without merging**
